# Generated by Django 2.1.3 on 2018-11-26 04:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n', models.CharField(max_length=50)),
                ('v', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Jinx',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('content', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Sentence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sen_reason', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reason', to='jinxjinx.Data')),
                ('sen_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='result', to='jinxjinx.Data')),
            ],
        ),
    ]
