# Generated by Django 2.1.3 on 2018-11-29 06:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jinxjinx', '0004_category_noun_verb'),
    ]

    operations = [
        migrations.CreateModel(
            name='Situation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=50)),
                ('feeling', models.CharField(max_length=50)),
                ('weather', models.CharField(max_length=50)),
                ('sentence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sentence', to='jinxjinx.Sentence')),
            ],
        ),
    ]
