# Generated by Django 2.1.3 on 2018-11-30 09:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('jinxjinx', '0007_sentence_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSentence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='sentence',
            name='user',
        ),
        migrations.AddField(
            model_name='usersentence',
            name='sentence',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jinxjinx.Sentence'),
        ),
        migrations.AddField(
            model_name='usersentence',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sentence',
            name='user',
            field=models.ManyToManyField(through='jinxjinx.UserSentence', to=settings.AUTH_USER_MODEL),
        ),
    ]
