# Generated by Django 2.1.3 on 2018-12-03 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jinxjinx', '0009_auto_20181203_0526'),
    ]

    operations = [
        migrations.AddField(
            model_name='sentence',
            name='count',
            field=models.IntegerField(default=0),
        ),
    ]
