# Generated by Django 2.1.3 on 2018-12-03 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jinxjinx', '0010_sentence_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='result',
            field=models.CharField(max_length=50),
        ),
    ]
